version: "3"

services:

    influxdb:
      image: influxdb:2.4
      container_name: influxdb
      restart: always
      environment:
        - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
        - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
        - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
        - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
        - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
        - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
        - INFLUXD_LOG_LEVEL=${INFLUXD_LOG_LEVEL}
        - TZ=${TZ}
      volumes:
        - "./data/influxdb2/conf:/etc/influxdb2"
        - influxdb_data:/var/lib/influxdb2
      ports:
        - ${INFLUXDB_HTTP_PORT}:8086
      networks:
        - ${NETWORK}
      privileged: true

    
    grafana:
      image: grafana/grafana-oss:9.1.7
      container_name: grafana
      environment:
        - GF_SECURITY_ADMIN_USER=${GRAFANA_SECURITY_ADMIN_USER}
        - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_SECURITY_ADMIN_PASSWORD}
      links: 
        - influxdb:influxdb
      depends_on:
        - influxdb
      restart: always
      ports:
        - ${GRAFANA_HTTP_PORT}:3000
      volumes: 
        - grafana_data:/var/lib/grafana
      networks: 
        - ${NETWORK}
      privileged: true

volumes: 
    influxdb_data:
    grafana_data:

networks: 
    ${NETWORK}:
        external: true